name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m venv venv
      - run: venv/bin/pip install -r requirements.txt
      - run: venv/bin/python -m unittest
